title: Gamechangers in STEM
description: > # this means to ignore newlines until "baseurl:"
  A two day collaborative hackathon focused on improving
  diversity in Science, Technology, Engineering and Mathematics
baseurl: "" # the subpath of your site, e.g. /blog
url: "STEMGamechangers.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

#logo: "../css/2016_style/img/icon-large.png"
logo: "../css/2018_style/img/logos/noun_women in technology_102228.png"

social:
  name: Your Facebook Page
  link: "https://www.facebook.com/"

#google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
