title: Gamechangers for Diversity in STEM
description: > # this means to ignore newlines until "baseurl:"
  A two day collaborative event focused on improving
  diversity in Science, Technology, Engineering and Mathematics
baseurl: "" # the subpath of your site, e.g. /blog
url: "STEMGamechangers.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

#logo: "../css/2016_style/img/icon-large.png"
logo: "../css/2018_style/img/logos/noun_people_group_1844354_cropped.png"

#google_site_verification: googleXXXXXXXXXXXXXXXX.html

#include: ['_2016_pages', '_2018_pages']
include: ['_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: https://stemgamechangers.slack.com/
  - title: twitter
    url: https://twitter.com/stemgamechange
  - title: facebook
    url: https://www.facebook.com/STEMgamechangers/
  - title: github
    url: https://github.com/stemgamechangers/stemgamechangers.github.io

# Build settings
markdown: kramdown
permalink: pretty
