title: Data Science For Experimental Design
description: > # this means to ignore newlines until "baseurl:"
  Harnessing the power of data science for experimental research
baseurl: "" # the subpath of your site, e.g. /blog
url: "DataDrivenExperimentalDesign.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

#logo: "../css/2016_style/img/icon-large.png"
logo: "../css/2018_style/img/logos/noun_Robot_960071_cropped_white.png"

#google_site_verification: googleXXXXXXXXXXXXXXXX.html

#include: ['_2016_pages', '_2018_pages']
include: ['_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?f=tweets&q=%23TuringDSED
  - title: github
    url: https://github.com/datascienceforexperimentaldesign/datascienceforexperimentaldesign.github.io

# Build settings
markdown: kramdown
permalink: pretty
